### ISSUE TITLE
ssd_mobilenet_v2.config file

### ISSUE THREAD

**Issue by yair-6over6** [inovex/tensorflow-lite-demo#2]
Hi,
Thanks you so much for this VERY useful repo + post!

I can't find the configuration file:
../../../model/ssd_mobilenet_v2/ssd_mobilenet_v2.config
any help will be appreciated :)

**Comment by RobinBaumann** [comment]
Appreciate your feedback.

It seems like I accidentally deleted the file while I was removing some old clutter. It should be there now.

**Comment by yair-6over6** [comment]
Awesome, thanks a lot!
